### PR TITLE
check container content is null

### LINKED ISSUE #2: NRE if AutohideActionView is false by default
ShowActionView method throw NRE:
_actionViewContainer.Content.FadeTo(1.0d, easing: Easing.CubicInOut);

Please check _actionViewContainer is not null

### PR DESCRIPTION
**Pull request by VladislavAntonyuk**
fix #2

### CODE REVIEW

**Comment by mariusmuntean** [comment]
Hey @VladislavAntonyuk ,

Thanks for your PR!
I had a look at it and I'm willing to merge it after you adjust it a bit.

First, it says it fixes #2  but actually it does a bit more, like extending the sample with SwipeViews. I didn't see any value in that; the sample should highlight what the coordinator layout can do.

Then I noticed that you updated Xamarin.Forms but I think the lib should reference an older version, thus allowing developers to integrate it into their projects without forcing them to also upgrade Xamarin.Forms. From my understanding the lib can declare a dependency on version x and be used in an app that uses version x and higher.

Looking forward for your contribution!

**Comment by VladislavAntonyuk** [comment]
I thought issue #1 may be solved by simple update of Xamarin Forms. I will downgrade it.

As for the sample, it a test to display the issue #1. Looks like Input and CascadeInput do not work as expected. Swipe actions and even button clicks don’t work. Event doesn’t occur.

**Comment by VladislavAntonyuk** [comment]
@mariusmuntean any updates?

**Comment by mariusmuntean** [comment]
I will have some time next weekend to have a closer look. 
It is excellent of you to provide a fix for the NRE in this PR. I don't think it makes sense to also include updates to the sample which highlight another issue. I would prefer if you create the smallest possible project (doesn't have to be based on the sample app) that reproduces the issue and then link to it in the respective issue.

**Pull request closed without merging**
